WP-6: Inbox Page Translations
Zydex/asiga-i18n pull request #12
Opened 2024-06-03 03:45 UTC by Tom-Leigh

2024-06-24 22:20 UTC, ericholm approved these changes

2024-06-24 22:21 UTC, ericholm requested changes
Looks fine but you should resolve the conflicts

2024-06-26 23:29 UTC, ellabellla approved these changes

2024-06-26 23:35 UTC, ericholm approved these changes

2024-06-27 00:23 UTC, merged